lint:
  modules_config: False
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - docs/images/nf-core-raredisease_logo_dark.png
    - docs/images/nf-core-raredisease_logo_light.png
    - assets/nf-core-raredisease_logo_light.png
repository_type: pipeline
nf_core_version: "2.14.1"
